# Generated by Django 4.0.2 on 2022-03-02 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_address',
        ),
        migrations.AlterField(
            model_name='student',
            name='role_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orm.role'),
        ),
        migrations.AlterModelTable(
            name='student',
            table='student',
        ),
    ]
