# Generated by Django 4.0.2 on 2022-03-03 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_remove_student_student_address_alter_student_role_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time', models.TimeField()),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'developer',
            },
        ),
        migrations.CreateModel(
            name='ProjectManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pmanager_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED')], max_length=200)),
                ('developer1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orm.developer')),
                ('projectmanager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orm.projectmanager')),
            ],
            options={
                'db_table': 'project1',
            },
        ),
    ]
