# Generated by Django 4.0.2 on 2022-02-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_table_alter_projectcategory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
